name: Lidar_Seg
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - addict=2.4.0=pyhd8ed1ab_2
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - einops=0.8.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.9.0=pyhff2d567_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.11.0=py310hbe37b52_0
  - hdf5=1.12.1=h2b7332f_3
  - huggingface_hub=0.25.1=pyhd8ed1ab_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=7_ha36c22a_netlib
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcurl=7.88.1=h251f7ec_2
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.2=0
  - libnvfatbin=12.6.68=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py310h6a678d5_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plyfile=1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cluster=1.6.3=py310_torch_2.4.0_cu124
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.4.0_cu124
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - safetensors=0.4.5=py310h505e2c1_0
  - scipy=1.14.1=py310ha3fb0e1_0
  - setuptools=75.1.0=py310h06a4308_0
  - sharedarray=3.2.4=py310hf462985_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.18.0=pyhd8ed1ab_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - timm=1.0.9=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.4.1=py310_cu124
  - torchtriton=3.0.0=py310
  - torchvision=0.19.1=py310_cu124
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - werkzeug=3.0.4=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.40.1=pyhd8ed1ab_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - aiohappyeyeballs==2.4.2
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - appnope==0.1.4
      - apptools==5.3.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - backcall==0.2.0
      - blinker==1.8.2
      - cachelib==0.9.0
      - cachetools==5.5.0
      - ccimport==0.4.3
      - chardet==5.2.0
      - click==8.1.7
      - clip==1.0
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.9
      - contourpy==1.3.0
      - cumm-cu120==0.4.11
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-extensions==1.0.18
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclass-wizard==0.22.3
      - decorator==5.1.1
      - descartes==1.1.0
      - editorconfig==0.12.4
      - entrypoints==0.4
      - envisage==7.0.3
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fire==0.6.0
      - flash-attn==2.6.3
      - flask==3.0.3
      - flask-caching==2.3.0
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - ftfy==6.2.3
      - gmplot==1.4.1
      - grpcio==1.66.2
      - hdbscan==0.8.38.post1
      - ipython==8.29.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jsbeautifier==1.15.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lark==1.2.2
      - markdown==3.7
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mayavi==4.8.2
      - more-itertools==10.5.0
      - multidict==6.1.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - numpy==1.24.1
      - nuscenes-devkit==1.1.11
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - pandaset==0.3.dev0
      - parso==0.8.4
      - pccm==0.4.16
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - plotly==5.24.1
      - pooch==1.8.2
      - portalocker==2.10.1
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==2.13.6
      - pycocotools==2.0.8
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyface==8.0.0
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - pyquaternion==0.9.9
      - pyrsistent==0.20.0
      - pyvista==0.44.1
      - pyviz3d==0.3.5
      - referencing==0.35.1
      - regex==2024.9.11
      - retrying==1.3.4
      - rpds-py==0.21.0
      - ruff==0.4.10
      - scikit-learn==1.5.2
      - scooby==0.10.0
      - shapely==1.8.5.post1
      - spconv-cu120==2.3.6
      - stack-data==0.6.3
      - tenacity==9.0.0
      - tensorboard-data-server==0.7.2
      - testpath==0.6.0
      - threadpoolctl==3.5.0
      - torch-geometric==2.6.1
      - traitlets==5.14.3
      - traits==6.4.3
      - traitsui==8.0.0
      - transforms3d==0.4.2
      - types-python-dateutil==2.9.0.20240906
      - tzdata==2024.1
      - uri-template==1.3.0
      - vtk==9.3.1
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - widgetsnbextension==4.0.13
      - yarl==1.13.1
prefix: /home/thor/anaconda3/envs/Lidar_Seg
